feat: test-pre-python GHA for testing on latest python pre-release version.
hpcflow/python-release-workflow pull request #39
Opened 2023-06-06 14:29 UTC by fherreazcue

Same as test workflow, but not involving CentOS.
Selects latest pre-release version to test on.
Manually invoked.

2023-06-07 11:03 UTC, aplowman requested changes

2023-06-08 17:55 UTC, aplowman commented on .github/workflows/test_pre_python.yml.in
> +          - "latest"
I think that's just the most recent GitHub release in that repository -- now it's changed to 3.7.17.

2023-06-09 10:04 UTC, fherreazcue commented on .github/workflows/test_pre_python.yml.in
> +          - "latest"
You are right... that is a very odd use of the "latest" tag... I've changed it to 3.12-dev.

2023-06-09 17:02 UTC, aplowman approved these changes

2023-06-12 08:18 UTC, merged